package constant;

public class IMPLConstants {
    public static final String INDEX_URL = "/index.jsp";
    public static final String LOG_IN = "/login";
    public static final String LOG_IN_URL = "/login.jsp";
    public static final String LOGOUT = "/logout";
    public static final String REGISTRATION = "/registration";
    public static final String USER_EDIT = "/update";
    public static final String USER_EDIT_BY_ADMIN = "/manage/edit_user_by_admin";
    public static final String USER_EDIT_BY_ADMIN_PARAMETER ="/manage/edit_user_by_admin_button" ;
    public static final String USER_UPDATE_PASSWORD ="/update_password" ;
    public static final String HOME_PAGE_URL = "/homepage.jsp";
    public static final String HOME_PAGE = "/homepage";
    public static final String CASHBOX = "/cashbox";
    public static final String CASHBOX_URL = "/cashbox.jsp";
    public static final String ERROR_URL = "/error.jsp";
    public static final String SHOW_USER_LIST_URL = "/show_users.jsp";
    public static final String SHOW_TOUR_LIST_ADMIN_URL = "/show_tours.jsp";
    public static final String SHOW_SERVICE_LIST_ADMIN_URL = "/show_my_contract.jsp";
    public static final String SHOW_COUNTRY_LIST_ADMIN_URL = "/show_countries.jsp";
    public static final String EDIT_COUNTRY_URL = "/edit_country.jsp";
    public static final String CONTRACT = "/contract";
    public static final String CONTRACT_URL = "/contract.jsp";
    public static final String TOUR_CONTRACT = "/tour_contract";
    public static final String FINAL_CONTRACT = "/final_contract";
    public static final String SHOW_ALL_CONTRACT = "/manage/show_all_contract";
    public static final String SHOW_ALL_CONTRACT_URL = "/show_all_contract.jsp";
    public static final String DELETE_CONTRACT = "/manage/delete_contract";
    public static final String TOUR_LIST = "/tour_list";
    public static final String TOUR_LIST_BY_COUNTRY = "/tour_list_by_country";
    public static final String EDIT_TOUR_BUTTON = "/manage/edit_tour_button";
    public static final String EDIT_TOUR = "/manage/edit_tour";
    public static final String EDIT_TOUR_URL = "/edit_tour.jsp";
    public static final String CREATE_TOUR = "/manage/create_tour";
    public static final String DELETE_TOUR = "/manage/delete_tour";
    public static final String SHOW_USER_LIST = "/manage/show_user_list";
    public static final String SHOW_COUNTRY = "/show_country";
    public static final String DELETE_USER_BY_ADMIN = "/manage/delete_user_by_admin";
    public static final String CREATE_COUNTRY = "/manage/create_country";
    public static final String DELETE_COUNTRY = "/manage/delete_country";
    public static final String EDIT_COUNTRY = "/manage/edit_country";
    public static final String EDIT_COUNTRY_PARAMETER = "/manage/edit_country_parameter";
    public static final String EDIT_USER_BY_ADMIN = "/edit_user_by_admin.jsp";
    public static final String CHANGE_LANGUAGE = "/change_language";
    public static final String SHOW_MY_CONTRACT = "/show_my_contract";
    public static final String NAME = "name";
    public static final String NAME_RU = "name_ru";
    public static final String NAME_ENG = "name_eng";
    public static final String PRICE = "price";
    public static final String DURATION = "duration";
    public static final String DESCRIPTION = "description";
    public static final String DESCRIPTION_RU = "description_ru";
    public static final String DESCRIPTION_ENG = "description_eng";
    public static final String GENDER = "gender";
    public static final String IIN = "iin";
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String EMAIL = "email";
    public static final String ID = "id";
    public static final String LAST_NAME = "lastName";
    public static final String FIRST_NAME = "firstName";
    public static final String ADDRESS = "address";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String DATE_OF_IIN = "dateOfIIN";
    public static final String USER = "user";
    public static final String ROLE = "role";
    public static final String IS_ADMIN = "isAdmin";
    public static final String TRUE = "true";
    public static final String USER_LIST = "userList";
    public static final String TOUR = "tour";
    public static final String TOUR_START_DATE = "tourStartDate";
    public static final String TOUR_FINISH_DATE = "tourFinishDate";



    static final int FILE_SIZE = 1024000;
}
